### ISSUE TITLE
Unable to set up nodes on a local private Neo chain using  neo-cli

### ISSUE THREAD

**Issue by alexy97** [neo-project/neo-node#542]
I have been following this guide https://docs.neo.org/docs/en-us/network/private-chain/private-chain2.html#installing-plug-in  on creating a private neo blockchain locally. I created 4 directories for the consensus nodes, extracted the neo-cli.zip in each of them , and configured the config.json and protocol.json files according to the instructions (setting up ports etc). However, I am unable to start the nodes simultaneously and this is the error im getting: 

System.TypeInitializationException
The type initializer for 'Neo.Settings' threw an exception.
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

System.ArgumentNullException
Value cannot be null.
Parameter name: format
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Neo.PathsSettings..ctor(IConfigurationSection section)
   at Neo.Settings..ctor(IConfigurationSection section)
   at Neo.Settings..cctor()

I am unsure what I have done wrong as I have followed the guide closely.

**Comment by ryanfalzon** [comment]
Any updates on this, please? Have been trying to solve the exact same issue for the past day now.

**Comment by ProDog** [comment]
Take a look your config.json?
