### ISSUE TITLE
can't use "ImportBlocks" plugin

### ISSUE THREAD

**Issue by hundredlee** [neo-project/neo-node#543]
use the Full Offline Package.

neo-cli version : 3.0.0-preview1
system: ubuntu 16.06

show error info:
[ERROR][2/12/20 4:18:57 PM][Thread 0005][akka://NeoSystem/user/$d] One of the identified items was in an invalid format.
Cause: System.FormatException: One of the identified items was in an invalid format.
   at Neo.Network.P2P.Payloads.BlockBase.Deserialize(BinaryReader reader)
   at Neo.Network.P2P.Payloads.Block.Deserialize(BinaryReader reader)
   at Neo.IO.Helper.ReadSerializable[T](BinaryReader reader)
   at Neo.IO.Helper.AsSerializable[T](Byte[] value, Int32 start)
   at Neo.Plugins.BlockImporter.GetBlocks(Stream stream, Boolean read_start)+MoveNext()
   at Neo.Plugins.BlockImporter.GetBlocksFromFile()+MoveNext()
   at Neo.Plugins.BlockImporter.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Comment by shargon** [comment]
Are you using neo2 binaries?
