### ISSUE TITLE
node: Error when exiting

### ISSUE THREAD

**Issue by asifshiraz** [neo-project/neo-node#701]
In version 2.12.2.0, I see the following error on the exit command in neo-cli

`neo> exit
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$3b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Zb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Pb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$gc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Xb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$1b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Ub] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$cc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$0b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$lc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$~b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$fc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$jc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$+b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$pc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$sc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$ec] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$nc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$dc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Ob] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$mc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$oc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Hc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$qc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Dc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Gc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Ic] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Bc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$tc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Jc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Ac] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$zc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$xc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$8b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$kc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$2b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Wb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$7b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$9b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Rb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Vb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Sb] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$Cc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$5b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$4b] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][12/21/2020 9:40:42 PM][Thread 0017][akka://NeoSystem/system/IO-TCP/$vc] Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#697806960]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)`

**Comment by Tommo-L** [comment]
Thank you for your feedback. 

`exit` command has not been fixed yet, plz use `ctl + c`.

**Comment by shargon** [comment]
Old, if remains, please re-open
