### ISSUE TITLE
RPCServer call on ConsoleServiceBase

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-node#729]
`https://github.com/neo-project/neo-node/blob/31bb3ca90ec4122cf320390569b72e8451cabde3/Neo.ConsoleService/ConsoleServiceBase.cs#L482`

```cs
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RpcServer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'RpcServer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at Neo.ConsoleService.ConsoleServiceBase.RegisterCommand(Object instance, String name) in /opt/neoNode/Neo.ConsoleService/ConsoleServiceBase.cs:line 482
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
/opt/start_node.sh: line 2:    92 Aborted                 (core dumped) dotnet neo-cli.dll
```

Is it compulsory?

**Comment by vncoelho** [comment]
Closed because it was an error that I forgot to delete `StateService.dll` file.
