### ISSUE TITLE
node: 3.4.0 ?????????

### ISSUE THREAD

**Issue by hotcoin-walle** [neo-project/neo-node#878]
操作如下：(除了安装插件未做任何操作，包括同步、配置也是全新开始)

neo> plugins
Loaded plugins:
        LevelDBStore@3.4.0.0     Uses LevelDB to store the blockchain data
neo> install ApplicationLogs
From https://github.com/neo-project/neo-modules/releases/download/v3.4.0/ApplicationLogs.zip
Downloading ApplicationLogs.zip 5KB/5KB 100%
SHA256: 5b918c6907f9ec63e80f01b685a1d16acfb6e21f6bec4d3b2e37686dcd010b90
Installing dependency: RpcServer
From https://github.com/neo-project/neo-modules/releases/download/v3.4.0/RpcServer.zip
Downloading RpcServer.zip 29KB/29KB 100%
SHA256: 93f28eb3aadaaf523b6627b3183e1969f9ebf038827e4e10c7dba45c06bfbfdb
Warning: Install successful, please restart neo-cli.
neo> install RpcNep17Tracker
Error: One or more errors occurred. (Plugin doesn't exist.)
neo> plugins
Loaded plugins:
        LevelDBStore@3.4.0.0     Uses LevelDB to store the blockchain data
neo> exit
root@iZt4ngmvfd9uuedorwy1fmZ:/coins/neo/v3.4.0/neo-cli# ./neo-cli
NEO-CLI v3.4.0  -  NEO v3.4.0  -  NEO-VM v3.4.0

Unhandled exception. neo> System.TypeLoadException: Could not load type 'Neo.IO.Json.JArray' from assembly 'Neo, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'.
   at Neo.Plugins.RpcServer..ctor(NeoSystem system, RpcServerSettings settings)
   at Neo.Plugins.RpcServerPlugin.OnSystemLoaded(NeoSystem system)
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath)
   at Neo.CLI.MainService.Start(String[] args) in E:\Release\3.4.0\neo-node\neo-cli\CLI\MainService.cs:line 374
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted

**Comment by erikzhang** [comment]
要安装3.4.0版本的插件，旧的插件不能用了。

**Comment by hotcoin-walle** [comment]
> 要安装3.4.0版本的插件，旧的插件不能用了。

是在 neo-cli里边的console下安装的插件。install RpcServer，提示也是3.4.0版本的插件

**Comment by Liaojinghui** [comment]
新版本的把json的路径改了，所以所有的包括节点和插件都需要从新搞，如果你一直遇到这个问题，建议删掉插件文件夹，然后下载官方最新的neo-cli之后覆盖你本地的。然后重新安装所有的插件。

**Comment by shargon** [comment]
Old, if remains, please re-open
