### ISSUE TITLE
The given key 'LevelDBStore' was not present in the dictionary.

### ISSUE THREAD

**Issue by scharada** [neo-project/neo-node#881]
hi , i have followed exactly the installation steps as mentioned in the documentation. tried the published binaries and also running in visual studio from code. no changes to the code were made at all.

i get the same exception:

 [12:19:23.137] System.Collections.Generic.KeyNotFoundException
The given key 'LevelDBStore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath)
   at Neo.CLI.MainService.Start(String[] args) in D:\BlockChain\Neo\neo-node\neo-cli\CLI\MainService.cs:line 375
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'LevelDBStore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath)
   at Neo.CLI.MainService.Start(String[] args) in D:\BlockChain\Neo\neo-node\neo-cli\CLI\MainService.cs:line 375
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

what am i doing wrong or missing please ?

**Comment by Liaojinghui** [comment]
You can get it from here https://github.com/neo-project/neo-modules/releases

**Comment by shargon** [comment]
Old, if remains, please re-open
